export const FETCH_RELEASE_TOGGLES = 'FETCH_RELEASE_TOGGLES';
export const UPDATE_RELEASE_TOGGLES = 'UPDATE_RELEASE_TOGGLES';
export const FETCH_RELEASE_TOGGLES_FAILED = 'FETCH_RELEASE_TOGGLES_FAILED';

export const SHOW_EDIT_RELEASE_TOGGLES_MODAL = 'SHOW_EDIT_RELEASE_TOGGLES_MODAL';
export const HIDE_EDIT_RELEASE_TOGGLES_MODAL = 'HIDE_EDIT_RELEASE_TOGGLES_MODAL';

export const QUICK_TOGGLE = 'QUICK_TOGGLE';
export const QUICK_TOGGLE_SUCCESS = 'QUICK_TOGGLE_SUCCESS';
export const QUICK_TOGGLE_FAILED = 'QUICK_TOGGLE_FAILED';

export const REQUEST_EDIT_RELEASE_TOGGLE = 'REQUEST_EDIT_RELEASE_TOGGLE';
export const EDIT_RELEASE_TOGGLE_SUCCESS = 'EDIT_RELEASE_TOGGLE_SUCCESS';
export const EDIT_RELEASE_TOGGLE_FAILED = 'EDIT_RELEASE_TOGGLE_FAILED';
export const ON_EDIT_FORM_CATEGORY_CHANGED = 'ON_EDIT_FORM_CATEGORY_CHANGED';
export const ON_EDIT_FORM_NAME_CHANGED = 'ON_EDIT_FORM_NAME_CHANGED';
export const ON_EDIT_FORM_DESCRIPTION_CHANGED = 'ON_EDIT_FORM_DESCRIPTION_CHANGED';
export const ON_EDIT_FORM_ACTIVE_CHANGED = 'ON_EDIT_FORM_ACTIVE_CHANGED';
